### ISSUE TITLE
Cannot update desktop version

### ISSUE THREAD

**Issue by PapsOu** [jgraph/drawio-desktop#138]
Hello,

With the electron based application, I cannot update when the update prompt indicates that a new update is available.

Here the error message :

![20190806-094619](https://user-images.githubusercontent.com/5792207/62521189-75bff980-b82f-11e9-8f60-7941630f3990.png)

When launching the app via a terminal, this is printed when I the error appear :

```bash
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[09:47:02.028] [info] Checking for update
[09:47:04.246] [info] Found version 11.1.1 (url: draw.io-x86_64-11.1.1.AppImage)
[09:47:04.246] [info] @update-available@
 { version: '11.1.1',
  files:
   [ { url: 'draw.io-x86_64-11.1.1.AppImage',
       sha512:
        '/iiqDREBRf6Y+TZ4dEZSIUqxVSHdJ3Uu3moem/Kw8D7j+u/UWsGdHQq0tKymN03cQ0eO8sB7DzTVM7ohrvrBiQ==',
       size: 108927458,
       blockMapSize: 115494 } ],
  path: 'draw.io-x86_64-11.1.1.AppImage',
  sha512:
   '/iiqDREBRf6Y+TZ4dEZSIUqxVSHdJ3Uu3moem/Kw8D7j+u/UWsGdHQq0tKymN03cQ0eO8sB7DzTVM7ohrvrBiQ==',
  releaseDate: '2019-08-02T21:41:39.699Z',
  releaseName: '11.1.1',
  releaseNotes:
   `<p><strong>Important</strong> Pre 10.7.x users must upgrade for critical security fixes. If you've been redirected here, that's why.</p>\n<h2>Releases Notes for 11.1.1</h2>\n<p><a href="https://github.com/jgraph/drawio-desktop/releases/download/v11.1.1/draw.io-11.1.1-windows-installer.exe">Windows Installer</a><br>\n<a href="https://github.com/jgraph/drawio-desktop/releases/download/v11.1.1/draw.io-11.1.1-windows-no-installer.exe">Window No Installer</a><br>\n<a href="https://github.com/jgraph/drawio-desktop/releases/download/v11.1.1/draw.io-11.1.1.dmg">Mac</a><br>\nLinux - <a href="https://github.com/jgraph/drawio-desktop/releases/download/v11.1.1/draw.io-amd64-11.1.1.deb">deb</a>, <a href="https://github.com/jgraph/drawio-desktop/releases/download/v11.1.1/draw.io-amd64-11.1.1.snap">snap</a>, <a href="https://github.com/jgraph/drawio-desktop/releases/download/v11.1.1/draw.io-x86_64-11.1.1.AppImage">AppImage</a> or <a href="https://github.com/jgraph/drawio-desktop/releases/download/v11.1.1/draw.io-x86_64-11.1.1.rpm">rpm</a></p>\n<p><strong>ChangeLog:</strong></p>\n<ul>\n<li>Updates to <a href="https://github.com/jgraph/drawio/blob/v11.1.1/ChangeLog">draw.io 11.1.1</a>, changes from 10.9.5 to 11.1.1 are new in this desktop release.</li>\n<li>Adds .vsdx export to command line options</li>\n<li>Defaults to dark theme if MacOS is in dark mode.</li>\n<li>Updates to <a href="https://github.com/electron/electron/releases/tag/v6.0.0">Electron 6</a></li>\n</ul>` } undefined
[09:47:22.066] [info] Downloading update from draw.io-x86_64-11.1.1.AppImage
[09:47:22.110] [error] Error: Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
[09:47:22.111] [error] @error@
 Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'

(node:8007) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
(node:8007) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8007) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And a `ls -la` in `/opt/draw.io/resources` :
```bash
total 72564
drwxr-xr-x  3 root root     4096  1 août  11:48 .
drwxr-xr-x  5 root root     4096  1 août  12:35 ..
-rw-rw-r--  1 root root 73988713 11 juil. 18:53 app.asar
-rw-rw-r--  1 root root   296572 11 juil. 18:53 electron.asar
drwxr-xr-x 69 root root     4096  1 août  11:48 inspector
```

Why the file `app-update.yml` is missing ?

Additional infos :

```
OS: fedora 30 - kenel 5.1.20-300.fc30.x86_64
draw.io --version : 10.9.5
```

**Comment by davidjgraph** [comment]
I'm guessing you're probably hitting https://github.com/electron-userland/electron-builder/issues/4046. If fixing upstream doesn't resolve it, we can reopen.

For now, workaround is to manually install new version.

**Comment by PapsOu** [comment]
That's strange because there is not the same error message on related but ticket.

Mine is `Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'`, the related one is `ENOSYS: function not implemented, unlink '/run/user/1000/appimagelauncherfs/0001.AppImage'`

Do you have an example content of file `app-update.yml` that I can create manually to check if this is related to the electron-userland bug ?

**Comment by davidjgraph** [comment]
It's not a file we create, I assume electron-builder creates it.

**Comment by PapsOu** [comment]
OK Thanks

**Comment by davidjgraph** [comment]
I don't think it's either. https://github.com/electron-userland/electron-builder/issues/4119 has a hint that we can check for the existence of the file.

I'm still hoping that waiting a few weeks might fix this. Debugging new electron issues tends to disappear down a hole, we lack the resources for such diversions.

**Comment by PapsOu** [comment]
It is not related to how the application is packaged and published ?

There is nothing urgent (I'll won't update because the application works great under this version and I don't wait for additional features for now).

**Comment by davidjgraph** [comment]
I think it's https://github.com/electron-userland/electron-builder/issues/2736. The new electron-builder doesn't quite play right with Electron 6 yet, https://travis-ci.org/jgraph/drawio-desktop/jobs/567841093

Since the CI build was broken, I built them locally, but removed the publish step since I don't have the keys locally. I'll rebuild it later with placeholder values and see if we get our file back.

**Comment by flofrie** [comment]
I request to re-open this issue; I just downloaded the DrawIO deb file, installed it on Ubuntu 19.04, and I'm getting the exact same error, failing on the update process.

**Comment by marcdexet-cnrs** [comment]
Same problem with desktop 11.3.0 on ubuntu 18.0401

**Comment by Josef-Reichardt** [comment]
Still the same with 12.1.7 on ubuntu 18.04.3 LTS.

**Comment by acs** [comment]
Same issue using the flatpak version. 
```
flatpak run com.jgraph.drawio.desktop
...
08:04:00.565 › Downloading update from draw.io-x86_64-12.2.2.AppImage
08:04:00.581 › Error: Error: ENOENT: no such file or directory, open '/app/drawio-desktop/resources/app-update.yml'
08:04:00.582 › @error@
 Error: ENOENT: no such file or directory, open '/app/drawio-desktop/resources/app-update.yml'

```

**Comment by cs-at-ucy** [comment]
Same issue using rpm on CentOS Linux release 7.6.1810 (Core) 
I attach a file with the error messages from my terminal.
[draw.io.txt](https://github.com/jgraph/drawio-desktop/files/3900801/draw.io.txt)

**Comment by ijash** [comment]
same here in kubuntu 18.04

**Comment by naimen** [comment]
Same problem with the SNAP install on Ubuntu 18.04

**Comment by VGerris** [comment]
Indeed, exact same problem after using the command as documented, on Ubuntu 18.04:
`sudo snap install drawio
`
output after starting from command line:
```
drawio 
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
16:04:23.861 › Checking for update
16:04:23.912 › Generated new staging user ID: 0a711e7b-c419-57e8-8e9f-e56c0ce5fd9f
[6341:1204/160424.098795:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(node:6353) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:6353) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(electron) 'setZoomFactor function' is deprecated and will be removed. Please use 'zoomFactor property' instead.
16:04:26.717 › Found version 12.3.2 (url: draw.io-x86_64-12.3.2.AppImage)
16:04:26.717 › @update-available@
 {
  version: '12.3.2',
  files: [
    {
      url: 'draw.io-x86_64-12.3.2.AppImage',
      sha512: 'bURgbDKemHr15aC2oYeeo/7EzyIJEQ5WlxM18JeydiGUNfNrvn6u4Ljx5+LQWwZ63cGzRSSrBEc9Dprg/jEWYA==',
      size: 97276046,
      blockMapSize: 102562
    }
  ],
  path: 'draw.io-x86_64-12.3.2.AppImage',
  sha512: 'bURgbDKemHr15aC2oYeeo/7EzyIJEQ5WlxM18JeydiGUNfNrvn6u4Ljx5+LQWwZ63cGzRSSrBEc9Dprg/jEWYA==',
  releaseDate: '2019-11-27T23:51:59.570Z',
  releaseName: '12.3.2',
  releaseNotes: '<h2>Releases Notes for 12.3.2</h2>\n' +
    '<p><a href="https://github.com/jgraph/drawio-desktop/releases/download/v12.3.2/draw.io-12.3.2-windows-installer.exe">Windows Installer</a><br>\n' +
    '<a href="https://github.com/jgraph/drawio-desktop/releases/download/v12.3.2/draw.io-12.3.2-windows-no-installer.exe">Windows No Installer</a><br>\n' +
    '<a href="https://github.com/jgraph/drawio-desktop/releases/download/v12.3.2/draw.io-12.3.2.dmg">macOS</a><br>\n' +
    'Linux - <a href="https://github.com/jgraph/drawio-desktop/releases/download/v12.3.2/draw.io-amd64-12.3.2.deb">deb</a>, <a href="https://snapcraft.io/drawio" rel="nofollow">snap</a>, <a href="https://github.com/jgraph/drawio-desktop/releases/download/v12.3.2/draw.io-x86_64-12.3.2.AppImage">AppImage</a> or <a href="https://github.com/jgraph/drawio-desktop/releases/download/v12.3.2/draw.io-x86_64-12.3.2.rpm">rpm</a><br>\n' +
    '<a href="https://chrome.google.com/webstore/detail/drawio-desktop/pebppomjfocnoigkeepgbmcifnnlndla/reviews" rel="nofollow">Google Chrome OS</a></p>\n' +
    '<p><strong>ChangeLog:</strong></p>\n' +
    '<ul>\n' +
    '<li>Updates to <a href="https://github.com/jgraph/drawio/blob/v12.3.2/ChangeLog">draw.io 12.3.2</a>, changes from, and including, 12.2.3 to 12.3.2 are new in this desktop release.</li>\n' +
    '<li>Updates to <a href="https://github.com/electron/electron/releases/tag/v7.1.2">Electron 7.1.2</a></li>\n' +
    '<li>Fixes issue where all zeros are written to file <a class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="511338873" data-permission-text="Issue title is private" data-url="https://github.com/jgraph/drawio-desktop/issues/170" data-hovercard-type="issue" data-hovercard-url="/jgraph/drawio-desktop/issues/170/hovercard" href="https://github.com/jgraph/drawio-desktop/issues/170">#170</a></li>\n' +
    '</ul>'
} undefined
Gtk-Message: 16:04:26.938: GtkDialog mapped without a transient parent. This is discouraged.
16:04:29.978 › Downloading update from draw.io-x86_64-12.3.2.AppImage
16:04:30.023 › Error: Error: ENOENT: no such file or directory, open '/snap/drawio/8/resources/app-update.yml'
16:04:30.023 › @error@
 Error: ENOENT: no such file or directory, open '/snap/drawio/8/resources/app-update.yml'
(electron) 'setClosable function' is deprecated and will be removed. Please use 'closable property' instead.
(node:6083) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/snap/drawio/8/resources/app-update.yml'
(node:6083) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/snap/drawio/8/resources/app-update.yml'
(node:6083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6083) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6083) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[6341:1204/160430.041121:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```
and indeed the file doesn't seem to exist so it seems like a bug?
ls -lrt /snap/drawio/8/resources
total 74748
-rw-r--r-- 1 root root 76541353 nov  7 12:40 app.asar

**Comment by davidjgraph** [comment]
Yes, it's a bug, thus the bug label on the issue. I think we've plenty of reports, thanks for these and the details, but now we need someone to move towards a fix.

**Comment by gsbhasin123** [comment]
Yes, having it on 19.10 and a Manjaro system
Don't we need https://github.com/electron-userland/electron-builder/issues/4233 to be closed first?

**Comment by gsbhasin123** [comment]
@davidjgraph is there an option to disable it? I'm sick of it telling me to update every time...

**Comment by uocxp** [comment]
ubuntu 18.04 same issue also. Installed using snap.

**Comment by wiserweb** [comment]
For those who arrive here via search engine. This issue is resolved with latest 12.5.3 release.
[Desktop releases](https://github.com/jgraph/drawio-desktop/releases)

> 
> Updater issues with 12.4.2 : Desktop 12.4.2 was released with a combination of Electron and Electron-Builder that has a bug causing updating to fail with the message "Error: Redirect was cancelled"
> 
> 12.5.3 has a fix for the issue in, but we don't have any mechanism to change the behaviour in the installed base for 12.4.2, so please install using the relevant full installer below.

**Comment by davidjgraph** [comment]
@wiserweb that isn't the same issue.

**Comment by PaluMacil** [comment]
Same issue occurs for me with the same dialog. Now saure anyone posted syslog, so I'm adding it:
```
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]:   path: '/snap/drawio/11/resources/app-update.yml',
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]:   stack: "Error: ENOENT: no such file or directory, open '/snap/drawio/11/resources/app-update.yml'"
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]: }
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]: (electron) 'setClosable function' is deprecated and will be removed. Please use 'closable property' instead.
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]: (node:773593) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/snap/drawio/11/resources/app-update.yml'
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]: (node:773593) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/snap/drawio/11/resources/app-update.yml'
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]: (node:773593) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]: (node:773593) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]: (node:773593) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Jul 25 15:17:59 my-box drawio_drawio.desktop[773593]: (node:773593) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by PaluMacil** [comment]
Of note, the upstream repo closed this issue without comment: https://github.com/electron-userland/electron-builder/issues/2736 I guess don't hold your breath for a fix. We could try updating electron-builder to the latest version, but it's only one minor release behind, it seems. The upstream repo closed the issue a long time ago as obselete.

**Comment by crnisamuraj** [comment]
Year later bug still present on any Ubuntu version or flavor I tried. Any ETA on fix?

`19:34:53.954 › Error: Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
19:34:53.955 › @error@
 Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
(node:30161) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
(node:30161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30161) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

**Comment by TheAssassin** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/4046#issuecomment-699743169.

**Comment by SolidWallOfCode** [comment]
Still broken - I had this precise error on Fedora 32.

**Comment by PaluMacil** [comment]
@SolidWallOfCode are you using Snap on the latest/edge channel? I noticed today that it's 15 months behind latest/stable. I didn't get the error after I restarted post switching channels, but I guess I'll know for sure the next time there is an update

**Comment by bioinfornatics** [comment]
I encounter the same error here.
I do not use snap to save my computer memory.

**Comment by coderGambit** [comment]
I have the same error on Fedora 34, I ended up manually downloading and installing the rpm

**Comment by davidjgraph** [comment]
We've deleted the edge channel, hopefully shouldn't happen on snap now.

**Comment by Ldev007** [comment]
I can confirm it is still failing to update on Pop OS 20.04 based on Ubuntu 20.04. Same error occurs. Although, installation was done using deb file (not snap) which I downloaded from the official website. The solution remains same **manual updation by installing new version deb file**

**Comment by davidjgraph** [comment]
This thread is such a mess there is no hope of understanding it. This is why we must have one issue per distinct problem.

**Comment by AlexanderAdelAU** [comment]
I am blissfully unaffected by what appear to be many spurious issues but have been impressed with the moderator’s willingness to either close or respond.  But what I really hope is that all this un-necessary traffic does not dampen the spirit or enthusiasm  of the developers and moderators of what is a damn fine tool.

 

Maybe a suggestion that might help dampen the amount of traffic could be to forcefully reject any but submissions that to not comply with the required format and rejecting any free format submissions and that any response to an issue gain weight (if necessary) by some simply up-vote or down-vote mechanism thus also cutting down of verbose traffic.

 

Alex

**Comment by tsilvs** [comment]
Having same ussue on Ubuntu 20.04

**Comment by praksharma** [comment]
This error still exists in 2022 on Ubuntu 20 LTS.

**Comment by sidx64** [comment]
This error still occurs, even if I have the latest version installed on my Debian 11.

**Comment by juniorari** [comment]
Same error ocorring on Debian11 x64:

(...)
13:51:25.483 › Downloading update from drawio-x86_64-20.7.4.AppImage
13:51:25.511 › Error: Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
13:51:25.511 › @error@
 {
  constructor: 'Error',
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/draw.io/resources/app-update.yml',
  stack: "Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'"
}
(..)

Looks like the file  '/opt/draw.io/resources/app-update.yml' isn't exist:
┌──[juniorari@junior-ari]─[~] ll /opt/draw.io/resources/
total 88788
drwxrwxr-x 2 root root     4096 dez 26 19:33 ./
drwxrwxr-x 5 root root     4096 dez 26 19:33 ../
-rw-rw-r-- 1 root root 90907438 abr 29  2020 app.asar


Did anyone manage to solve it?

**Comment by tsilvs** [comment]
This issue has to be addressed somehow. If certain paths are different between distros, then it should reference a relative path or something from environment variables.

Seems like this issue should be re-opened.

**Comment by Abahafart** [comment]
Could anyone solve the issue? The issue happens in Ubuntu 22.04.2 LTS

**Comment by davidjgraph** [comment]
I unsubscribed to this thread a couple of years ago. If any of these posts has a point, you must open a new issue for it, this thread is dead.
