### ISSUE TITLE
Unintelligible characters in Draw.io snap package on Fedora 32

### ISSUE THREAD

**Issue by tromlet** [jgraph/drawio-desktop#368]
![draw-io-20200826-characters-not-displaying-file-open-dialog](https://user-images.githubusercontent.com/37060893/91355908-1327fb80-e7ac-11ea-93fc-91080d563b4c.png)

Screenshot basically shows it all - whenever I try to do a standard File > Open, I get this Nautilus window. It works! But it's completely unintelligible - I had to memorize where things were in an standard Nautilus (Files) window, and then use that to open and edit the Draw.io diagram I was looking for.

EDIT: I should add - this DOES NOT happen when I use the vanilla, desktop version of the application from Fedora 32's "Software" application. It looks like this [one is sourced from Flathub](https://flathub.org/apps/details/com.jgraph.drawio.desktop), I'm not sure if it's officially published there by jgraph or not - but the File > Open window seems to work fine.

**Comment by dlakatos847** [comment]
Same issue on most recent OpenSuSE Tumbleweed.
```
$ sudo snap install drawio
drawio 13.6.2 from draw.io (jgraph✓) installed
$ drawio
```

Create New Diagram -> Blank Diagram -> Create
File -> Save As

![image](https://user-images.githubusercontent.com/5465344/92596127-9fa2e580-f2a5-11ea-8853-a1fba1f07133.png)

```
$ snap version
snap                 2.45.3.1-1.11
snapd                2.45.3.1-1.11
series               16
opensuse-tumbleweed  20200906
kernel               5.8.4-1-default
```

**Comment by davidjgraph** [comment]
Is this also using the flathub version?

**Comment by dlakatos847** [comment]
> Is this also using the flathub version?

Would you please re-phrase the question? What do you mean by _this_ and _flathub version_?

**Comment by tromlet** [comment]
> Is this also using the flathub version?

Apologies, I worded my edit poorly on my initial post. 

I meant that the version of Draw.io included in Fedora's "Software" application (which - to the best of my knowledge - IS [the flatpak version available from Flathub](https://flathub.org/apps/details/com.jgraph.drawio.desktop) and IS NOT included as a native application in the distribution's repositories), and it works just fine. Text is displayed properly in the file picker dialog.

I only get this problem with the Snap package.

**Comment by ybrhue** [comment]
I have the same problem.

**Comment by vanheck** [comment]
I have the same problem, but it looks like a problem with Electron (all apps), not just for Draw.io. I have the same issue with [joplin app](https://github.com/laurent22/joplin).

**Comment by rafafallo** [comment]
Same issue with Draw.io 14..1.8 installed with Snap on Ubuntu 20.10. Information about Snap:

```
snap    2.48.2
snapd   2.48.2
series  16
ubuntu  20.04
kernel  5.4.0-64-generic
```

Messages in console:

```
Gtk-Message: 23:23:07.788: Failed to load module "gtk-vector-screenshot"
Gtk-Message: 23:23:07.788: Failed to load module "appmenu-gtk-module"

(drawio:68372): Gtk-WARNING **: 23:23:07.801: Theme parsing error: gtk.css:1565:23: 'font-feature-settings' is not a valid property name

(drawio:68372): Gtk-WARNING **: 23:23:07.805: Theme parsing error: gtk.css:3615:25: 'font-feature-settings' is not a valid property name

(drawio:68372): Gtk-WARNING **: 23:23:07.806: Theme parsing error: gtk.css:4077:23: 'font-feature-settings' is not a valid property name
23:23:07.991 › Checking for update
(node:68372) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:68492) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
23:23:09.529 › Update for version 14.1.8 is not available (latest version: 14.1.8, downgrade is disallowed).
Gtk-Message: 23:23:28.630: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by rafafallo** [comment]
By the way:

```
$ sudo aptitude search gtk-vector
i   gtk-vector-screenshot                               - takes screenshots of applications as PDF or SVG files         
$ sudo aptitude search appmenu-gtk-module
i A appmenu-gtk-module-common                           - Common files for GtkMenuShell D-Bus exporter                  
rmorales@rafathinkpad:~/Downloads$ 
```

**Comment by cvbraeuer** [comment]
I have the same problem:

```
Gtk-Message: 13:00:49.497: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:00:49.497: Failed to load module "xapp-gtk3-module"
13:00:49.597 › Checking for update
(node:9917) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
/usr/share/libdrm/amdgpu.ids: No such file or directory
(node:10021) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
13:00:50.455 › Update for version 14.1.8 is not available (latest version: 14.1.8, downgrade is disallowed).
Gtk-Message: 13:00:54.193: GtkDialog mapped without a transient parent. This is discouraged.
```

```
$ snap version
snap     2.48.2-1
snapd    2.48.2-1
series   16
manjaro  -
kernel   5.10.7-3-MANJARO
```

Will try a non-snap solution then.

**Comment by baermathias** [comment]
Same problem on Ubuntu 20.04 Snap. Is there any solution in sight for this problem?

**Comment by davidjgraph** [comment]
There are discussions at:

https://www.reddit.com/r/archlinux/comments/9i2jsc/electron_apps_discord_vscode_etc_show_little/
https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484
https://github.com/Kong/insomnia/issues/2614

regarding electron apps in snap packages. If anyone finds a solution in there, please let us know.

A workaround is to use a package other than snap.

**Comment by dagostinelli** [comment]
I get this in other electron applications installed via snap.  It seems to be a wider issue.  Is there a log entry somewhere that says which font it can't find?

**Comment by mardoqueo** [comment]
Also suffering this. Any workaround?

**Comment by BorderCloud** [comment]
[Workaround](https://computingforgeeks.com/install-draw-io-desktop-application-on-ubuntu-debian-fedora/):
`sudo dnf install https://github.com/jgraph/drawio-desktop/releases/download/v14.9.6/drawio-x86_64-14.9.6.rpm`

**Comment by davidjgraph** [comment]
The most popular comment on the reddit thread is to install noto-fonts-emoji. The original posting says to install ttf-dejavu, emoji covers the rest.

**Comment by vrossum** [comment]
Same problem here on Ubuntu 21.10 with drawio 15.7.3 install from snap
I have 
fonts-noto-color-emoji and fonts-dejavu*  installed.

Fixed when installing from the .deb and github.

**Comment by baermathias** [comment]
> Same problem here on Ubuntu 21.10 with drawio 15.7.3 install from snap I have fonts-noto-color-emoji and fonts-dejavu* installed.
> 
> Fixed when installing from the .deb and github.

Fixed when installing drawio from .deb or the mentioned fonts?

**Comment by arulrajnet** [comment]
I have cleared the font cache

```
fc-cache -r
```

Then open the snap flavour of drawio (16.1.2). The fonts displayed properly

![2022-01-10_05-55](https://user-images.githubusercontent.com/834529/148707465-094847e0-4276-42b3-8b24-3fc821ff5f34.png)

![2022-01-10_06-00](https://user-images.githubusercontent.com/834529/148707476-38bde531-e4ef-4c86-b3a7-54b977b8d60c.png)

But If I close and open the drawio, then the same issue came back. 

So the conclusion is every time before open drawio clear the font cache.

**Comment by davidjgraph** [comment]
The conclusion is don't use snap.

**Comment by Kstuart1992** [comment]
I think I may understand the issue - electron is using the common configuration method when scripting and the package manager reporting the results from the request to download fills in these fields - fetches the library and off we go.
If someone have explored the Common Configuration for a fix and came to a conclusion please let me know - if not below explains some reasoning from my basic understanding [all of about ~1] specific to this but experience elsewhere [not on this software]
Where I think the issue may be:
Snap is fetching this from your system request but, for instance for me on fedora - Native now supports and prefers flatpak, but rpm is the standard we all have used to get repos when our standard package mngr didn't have the apps you wanted. That being said as simple as electrons CC look, they leave it up to what is using it to handle the logic -> Snap is getting the request ie  rpm [foo bar http:snapd.io/bin.bang/args .... ] getting the repo prepared as it understands -> the package manager receives in an expected manner and will build the package as instructed ... but when in app, it is not pointing to; in this case the expected areas or making the proper preconfigured args to the system to be able to access the process on your os or by even have the expected r-w permissions when it gets there -> not sure of testing, testing order / exemptions in that testing package.
What we can learn / fix: 
On this end - a solution on a patch they manually do -> you can choose, as make quite clear you would anyway, understood, add in a packaged check/test or we can push the issue on reproduced and proved patch / mod works so they can configure a more proper delivery method to your end-user. Otherwise - Nothing, but I'm interested and I'll do my thing until I learn something or you call me a silly boy because of [x,y,z] and move on. 
- All my best, until then - if the maintainers here want me to share what I come to learn here or if you have a more appropriate method to have it handled. I'll differ if requested. If you rather not deal with this notification and to close the issue all together, I can host on my own page and you can choose to include a link to what ever documentation I create if you so choose. 
- cheers

**Comment by jayvdb** [comment]
Using the snap on openSUSE, running `fc-cache -r` before `drawio` does not fix the problem for me.

I already have openSUSE packages `google-noto-coloremoji-fonts` and `dejavu-fonts` installed

**Comment by davidjgraph** [comment]
We'll take PRs on this.

**Comment by derappelt** [comment]
After 2 years still no solution?
I've the same problem on Ubuntu 23.04 using the Snap Version.

**Comment by davidjgraph** [comment]
We're happy to accept PRs, but we're not going to spend time on it ourselves, we don't have the time.

**Comment by baermathias** [comment]
@davidjgraph is this issue solved or why was this closed?

**Comment by cnmicha** [comment]
@davidjgraph The issue still persists in version 21.7.5 (snap)

**Comment by davidjgraph** [comment]
I'm closing because the issue is 3 years old and there's no sign of a solution. My impression of snap is that it's not production quality, so I'm considering stopping publishing to snap.

**Comment by CelianGdfrd** [comment]
The problem seems to stop happening with the newest version of Ubuntu, 23.10

**Comment by cnmicha** [comment]
> The problem seems to stop happening with the newest version of Ubuntu, 23.10

This is not the case for me, the issue is still present.

**Comment by 00shorty** [comment]
same for me on Ubuntu 23.04

**Comment by davidjgraph** [comment]
> The following command fixed this for me on Ubuntu 24.04.1 LTS:

> rm -rf ~/.cache/fontconfig && sudo fc-cache -r -v

> Following this solution: https://askubuntu.com/questions/1224125/font-characters-displayed-as-squares-in-ubuntu-18-04

**Comment by rdlalmeida** [comment]
> > The following command fixed this for me on Ubuntu 24.04.1 LTS:
> 
> > rm -rf ~/.cache/fontconfig && sudo fc-cache -r -v
> 
> > Following this solution: https://askubuntu.com/questions/1224125/font-characters-displayed-as-squares-in-ubuntu-18-04

This worked for me! Thanks! I'm running Mint 22.1 Cinnamon and drawio v26.0.9
