### ISSUE TITLE
draw.io - Not a diagram file

### ISSUE THREAD

**Issue by cvmiranda13** [jgraph/drawio-desktop#485]
While doing works in draw.io, my computer suddenly shut down due to power interruption. Then when I open again my draw.io files it says that it's not a diagram file.

Please help me with this. I need to recover my works from there.

**Comment by mararad** [comment]
Hi,

what draw.io desktop version are you using? Could you attach diagram file here, please?

**Comment by cvmiranda13** [comment]
@mararad Hi. I'm using diagrams.net 14.2.9 version..


[BACKOFFICE WIREFRAME_01292021.zip](https://github.com/jgraph/drawio-desktop/files/5922125/BACKOFFICE.WIREFRAME_01292021.zip)


please see the file, I hope we can do something about it.

**Comment by cvmiranda13** [comment]
@mararad I hope you can help me with this.

**Comment by cvmiranda13** [comment]
> Hi,
> 
> what draw.io desktop version are you using? Could you attach diagram file here, please?

hi @mararad have you tried the diagram I sent? is it working on you?

**Comment by mararad** [comment]
Thanks. 

I checked your file in Chrome Incognito with diagrams.net 14.3.0 and see that same error as you. When the file was checked more, it shows up as file filled with zeros only. I am afraid it is not possible to restore this one.

Are you sure you used diagrams.net online 14.2.9? Where did you save the diagram, please?

Are you sure you weren't using draw.io desktop version? (we had a similar issue there earlier but it was fixed)

Thanks,

**Comment by cvmiranda13** [comment]
Hi @mararad this is the version I'm using, please see attached. I saved the diagram on my computer storage.

![Capture](https://user-images.githubusercontent.com/78467976/107297405-3a4e5d00-6aae-11eb-8495-3653f0209e81.JPG)

**Comment by mararad** [comment]
Thanks. You used this https://chrome.google.com/webstore/detail/diagramsnet-desktop/pebppomjfocnoigkeepgbmcifnnlndla/related?hl=en-GB which will be killed at some point.

Since we don't store, nor have access to our users' diagrams, I am afraid there is nothing we could do on our end (especially when it comes to all zero in the file). My suggestion would be to install desktop from here: https://github.com/jgraph/drawio-desktop/releases

Regards,

**Comment by cvmiranda13** [comment]
okay @mararad . Thank you.

**Comment by rjcox-evergreen** [comment]
I am having a similar issue with my file. I opened and worked with it using the desktop version of the app. I downloaded and installed the latest version today but it still persists. Even trying to open a backup / temp file is challenging; the dmtp file opened temporarily but after I saved it as a version 3 copy of the file in draw io format, the newly saved document did not open. How can I resolve this?

![image](https://user-images.githubusercontent.com/114108155/225429204-e6630899-283b-44e9-a5fd-dd708113d579.png)
